name: execute_shell_code

description: execute a shell script given in the inputs

inputs:
  script_parameter:
    description: "Parameters to execute code"
    required: true
    default: "python --version"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v1  
    - name: Execute code
      shell: bash
      run: |
        ${{inputs.script_parameter}}
