name: Platform PR Workflow

on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "pr"
      flow_type:
        type: string
        description: "type of flow to execute"
        required: true
    secrets:
      LANGCHAIN_API_KEY:
        description: "LangSmith API Key."
        required: true
      LANGCHAIN_TRACING_V2:
        description: "Control tracing capabilities"
        required: true
      AZURE_OPENAI_API_KEY:
        description: "Azure Open AI key."
        required: true
      AZURE_OPENAI_ENDPOINT:
        description: "Azure Open AI Endpoint."
        required: true

jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml
  execute-ml-job-pipeline:
    name: Execute ML Job Pipeline
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper
      - name: Prepare Job Execution Environment
        uses: ./.github/actions/prepare_job_environment
    
      - name: Execute Flow
        uses: ./.github/actions/execute_shell_code
        env:
            BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
        with:
            script_parameter: |
                python -u -m flows.${{ inputs.flow_type }}.flow
