name: Platform PR Workflow

on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "pr"
      flow_type:
        type: string
        description: "type of flow to execute"
        required: true
jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml
  execute-ml-job-pipeline:
    name: Execute ML Job Pipeline
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper
      - name: Prepare Job Execution Environment
        uses: ./.github/actions/prepare_job_environment
    
      - name: Execute Flow
        uses: ./.github/actions/execute_shell_code
        env:
            LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
            LANGCHAIN_TRACING_V2: ${{ secrets.LANGCHAIN_TRACING_V2 }}
            AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
            AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        with:
            script_parameter: |
                python -u -m flows.${{ inputs.flow_type }}.flow
