name: Register Datasets

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  run-registration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Job Agent
        uses: ./.github/actions/prepare_job_environment
      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper
      - name: Execute Dataset Registration
        uses: ./.github/actions/execute_shell_code
        with:
            script_parameter: |
                python -u -m mlops.upload_data
